services:
  reporting-pipeline:
    build: .
    volumes:
      - ./input_files:/data/input:Z
      - ./output:/data/output:Z
      - ./archive:/data/archive:Z
      - ./logs:/data/logs:Z
    container_name: reporting_pipeline
