services:
  reporting-pipeline:
    build: .
    volumes:
      - ./input_files:/data/input
      - ./output:/data/output
      - ./archive:/data/archive
      - ./logs:/data/logs
    container_name: reporting_pipeline

